AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Profile Service
Resources:
  ProfilesTable:
     Type: AWS::DynamoDB::Table
     Properties:
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: profiles

  ProfilesQuery:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: profiles_profiles_query
      Handler: functions/profiles/query.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBReadOnlyAccess

  ProfilesGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: profiles_profiles_get
      Handler: functions/profiles/get.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBReadOnlyAccess

  ProfilesPut:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: profiles_profiles_put
      Handler: functions/profiles/put.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess

  ProfilesDelete:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: profiles_profiles_delete
      Handler: functions/profiles/delete.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionUri: swagger.yml
      Variables:
        ProfilesGetName: !Ref ProfilesGet
        ProfilesPutName: !Ref ProfilesPut
        ProfilesDeleteName: !Ref ProfilesDelete
        ProfilesQueryName: !Ref ProfilesQuery
