AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Profile Service
Resources:
  ProfilesTable:
     Type: AWS::DynamoDB::Table
     Properties:
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: profiles

  ProfilesQuery:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: profiles_profiles_query
      Handler: functions/profiles/query.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBReadOnlyAccess
      # Events:
      #   GetResource:
      #     Type: Api
      #     Properties:
      #       Path: /profiles
      #       Method: get
  ProfilesGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: profiles_profiles_get
      Handler: functions/profiles/get.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBReadOnlyAccess
      # Events:
      #   GetResource:
      #     Type: Api
      #     Properties:
      #       Path: /profiles/{userId}
      #       Method: get

  ProfilesPut:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: profiles_profiles_put
      Handler: functions/profiles/put.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      # Events:
      #   PutResource:
      #     Type: Api
      #     Properties:
      #       Path: /profiles/{userId}
      #       Method: put

  ProfilesDelete:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: profiles_profiles_delete
      Handler: functions/profiles/delete.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      # Events:
      #   DeleteResource:
      #     Type: Api
      #     Properties:
      #       Path: /profiles/{userId}
      #       Method: delete

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      DefinitionUri: swagger.yml
      Variables:
        ProfilesGetName: !Ref ProfilesGet
        ProfilesPutName: !Ref ProfilesPutName
        ProfilesDeleteName: !Ref ProfilesDeleteName
        ProfilesQueryName: !Ref ProfilesQueryName
