AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Account Service
Resources:
  Authorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accounts_authorizer
      Handler: functions/authorizer/index.handler
      Runtime: nodejs6.10

  AuthorizerIp:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accounts_authorizer_ip
      Handler: functions/authorizer/ip.handler
      Runtime: nodejs6.10

  Authentication:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accounts_authentication_post
      Handler: functions/authentication/index.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess

  UsersPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accounts_users_post
      Handler: functions/users/post.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionUri: swagger.yml
      Variables:
        AuthorizerName: !Ref Authorizer
        AuthorizerIpName: !Ref AuthorizerIp
        AuthenticationName: !Ref Authentication
        UsersPostName: !Ref UsersPost
