AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Account Service
Resources:
  AccountsTable:
     Type: AWS::DynamoDB::Table
     Properties:
        TableName: accounts
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

  AccountsTenantIpTable:
     Type: AWS::DynamoDB::Table
     Properties:
        TableName: accounts_tenant_ip
        AttributeDefinitions:
          -
            AttributeName: ipAddress
            AttributeType: S
        KeySchema:
          -
            AttributeName: ipAddress
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

  Authorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accounts_authorizer
      Handler: functions/authorizer/index.handler
      Runtime: nodejs6.10

  AuthorizerIp:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accounts_authorizer_ip
      Handler: functions/authorizer/ip.handler
      Runtime: nodejs6.10

  AuthDebug:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accounts_auth_debug
      Handler: functions/auth-debug.handler
      Runtime: nodejs6.10

  AuthenticationPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accounts_authentication_post
      Handler: functions/authentication/post.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          PRIVATE_KEY: "__PRIVATE_KEY__"

  UsersPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accounts_users_post
      Handler: functions/users/post.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionUri: swagger.yml
      Variables:
        LambdaAlias: DEV

  # https://github.com/awslabs/serverless-application-model/issues/59
  AuthDebugPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AuthDebug
      Principal: apigateway.amazonaws.com

  AuthorizerPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Authorizer
      Principal: apigateway.amazonaws.com
      SourceAccount:
        Ref: "AWS::AccountId"

  AuthorizerIpPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AuthorizerIp
      Principal: apigateway.amazonaws.com

  AuthenticationPostPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AuthenticationPost
      Principal: apigateway.amazonaws.com

  UsersPostPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref UsersPost
      Principal: apigateway.amazonaws.com
