AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Account Service
Resources:
  AccountsTable:
     Type: AWS::DynamoDB::Table
     Properties:
        TableName: accounts
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

  Authorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accounts_authorizer
      Handler: functions/authorizer/index.handler
      Runtime: nodejs6.10
      Environment:
        Variables:
          PUBLIC_KEY: hogehoge

  AuthorizerIp:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accounts_authorizer_ip
      Handler: functions/authorizer/ip.handler
      Runtime: nodejs6.10

  AuthenticationPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accounts_authentication_post
      Handler: functions/authentication/post.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess

  UsersPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: accounts_users_post
      Handler: functions/users/post.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionUri: swagger.yml
      Variables:
        LambdaAlias: DEV

  # https://github.com/awslabs/serverless-application-model/issues/59
  AuthenticationPostPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AuthenticationPost
      Principal: apigateway.amazonaws.com
